### ISSUE TITLE
Question/bug(?): multithreading in indexing operation

### ISSUE THREAD

**Issue by yankovs** [CERT-Polska/ursadb#215]
Hey :)!

We have an ursadb instance (v1.5.1) running in production with the following config:
```shell
ursadb> config get
{
    "result": {
        "database_workers": 2,
        "iterator_gc_seconds": 86400,
        "max_merge_datasets": 16,
        "max_merge_files": 1000000,
        "query_max_edge": 2,
        "query_max_ngram": 16,
    },
    "type": "config"
}
```
Other than setting values in this config, there are no further modifications to the source code.

We noticed that there are 8 ursadb thread during indexing. However, it seems like only 2 of them are active:
![MicrosoftTeams-image (3)](https://github.com/CERT-Polska/ursadb/assets/49753115/4848c36c-146b-4809-8aee-3369bd4fad66)

Going over the code, it seems like at startup it creates 2 (`database_workers`) worker threads, right? Then, in `Index.cpp` it looks like it creates 4 threads designed to do the indexing it self. So it seems like for some reason the multithreading here doesn't work right. Also, the code itself seems to use only one core of the machine, but maybe this is by design.

**Comment by msm-code** [comment]
How do you run the indexing? Every command is (by design) only executed by a single task, so for example `index /samples` will be executed by a single worker thread. Every command is (also by design) atomic, so if indexing command crashes/is stopped in the middle, then no new data is saved to the database. 

Is it possible that this is the reason for the single-threadness you observe?

That's why I usually don't index files directly, but I use a auxillary script: https://github.com/CERT-Polska/mquery/blob/master/src/utils/index.py. It separates files into smaller batches and runs multiple indexing commands at once. Depending on your needs you might want to split the list of files you want to index and run a few separate concurrent commands.

Would this work for you?
