### ISSUE TITLE
Add a build ID to unreleased versions of Debian packages

### ISSUE THREAD

**Issue by icedevml** [CERT-Polska/ursadb#53]
As discussed in #44:

> Add a build ID to unreleased versions. So the commit after 1.3.0 will be build as 1.3.0+202012131 for example.

**Comment by msm-code** [comment]
And also the hard thing: add a build id to ursadb_version in `Version.h.in` (if it's possible at all?)

**Comment by chivay** [comment]
It's quite easy:
https://cmake.org/cmake/help/v3.0/command/string.html

it supports `string(TIMESTAMP ...)`

**Comment by msm-code** [comment]
timestamp :weltschmerz:. Do you think it's possible to use docker commit ID?

**Comment by chivay** [comment]
Sure, we can use a hash or something. But this is kinda crappy when it comes to comparing them.

**Comment by chivay** [comment]
Package manager might protest

**Comment by msm-code** [comment]
At least semver explicitly says that all releaess differing only by build metadata (stuff after `+`) can't be compared.

Also people that are not developers probably shouldn't install packages other than official releases :thinking:. If I understand correctly we build them to ensure that it works, but we're not going to distribute them to people.

I like the idea of using git hashes (especially in Version.h), because then you know exactly what version someone is using. OTOH build timestamp will not give us a slightest hint about source precise version.

**Comment by chivay** [comment]
:thinking: fair enough

So, ignore timestamp, append git commit hash (or at least some of its prefix)?

**Comment by msm-code** [comment]
I think so.

I mean, I certainly want to see git commit hash (or its prefix) in the version reported by the db. What we use for tagging .debs is another story, but I still like the determinism of commit IDs so I'd use them

Does it make sense?  :thinking:
